title: Justin's Blog
description: Where I share my thoughts, ideas, and projects. My main focus is on neural networks, artificial intelligence, and algorithmic trading.
show_downloads: true
google_analytics: true
theme: 
